# Submits a dependency graph and performs dependency review on every pull request
name: Dependency review for pull requests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
      with:
        ref: ${{ main }}
    - name: Set up the JDK used to run Gradle
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '8'
    - name:
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name" 
        echo 'Hi' > file.txt
        git add file.txt
        git commit -m "hacked"
        git push
    - name: Generate and submit dependency graph for the PR
      uses: gradle/actions/dependency-submission@v3
      with:
        build-scan-publish: true
        build-scan-terms-of-service-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-service-agree: "yes"
  
  dependency-review:
    needs: dependency-submission
    runs-on: ubuntu-latest
    steps:
    - name: Perform dependency review on Pull Request
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/dependency-review-action@v4
    - name: Perform dependency review on Push Request
      if: ${{ github.event_name == 'push' }}
      uses: actions/dependency-review-action@v4
      with:
        base-ref: ${{ github.event.before }}
        head-ref: ${{ github.event.after }}
